### ISSUE TITLE
Event listeners on #myButton

### ISSUE THREAD

**Issue by iliastsangaris** [petenut/typing-race#13]
looks like you're setting two event listeners on `#myButton` (consider a better name).

One [here](https://github.com/petenut/typing-race/blob/c21b0db37733dbc58b563623fdfc826694e498bf/index.html#L12-L14) and the other [here](https://github.com/petenut/typing-race/blob/c21b0db37733dbc58b563623fdfc826694e498bf/index.html#L21-L23). Pick one and consider moving it to the bottom of the `<body>` tag

**Comment by petenut** [comment]
CSS is completely gone for the page. Going to create my own CSS from start. Button is not there anymore.
