### ISSUE TITLE
large indentation spacing

### ISSUE THREAD

**Issue by iliastsangaris** [petenut/typing-race#14]
there's a lot of white space created by the indents in the [app.js file](https://github.com/petenut/typing-race/blob/master/app.js), consider changing your tab size. If you use sublime, [here's an example how](http://stackoverflow.com/questions/9474090/how-do-i-force-sublime-text-2-to-indent-two-spaces-per-tab).

**Comment by petenut** [comment]
fixed

**Comment by iliastsangaris** [comment]
is it fixed? I still see indentation of more than two spaces [here](https://github.com/petenut/typing-race/blob/72bd45726634d437cf5cf8ee257578ab48536734/Game/app.js)

**Comment by petenut** [comment]
It was fixed yesterday. I think I forgot to git ACP at the time since I was
bashing my head against the table from last nights lab. Thanks for the
additional issues!
