### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by iliastsangaris** [petenut/typing-race#17]
Not a big deal but you could refactor [hard-coded data](https://github.com/petenut/typing-race/blob/72bd45726634d437cf5cf8ee257578ab48536734/Game/app.js#L7-L13) in your file into a JSON file instead. If you do make a JSON file, just remember to include it in your HTML before your `app.js` so that it can access it.

**Comment by petenut** [comment]
Removed hardcode data from app.js and made a new file names.json. Games works.
