### ISSUE TITLE
Backspace causes Chrome screen to go to previous page

### ISSUE THREAD

**Issue by mnorelli** [petenut/typing-race#2]
Aw!  I almost made it to the end, but I backspaced to fix a typing error and navigated back to the start page by accident!  Can you make it so keypresses on the backspace key get ignore during the game?  I think it's key # 8

**Comment by emiliogomezlavin** [comment]
Agree with Michael. This is an important bug to be fixed for the user experience in the game ;)

**Comment by petenut** [comment]
No more main page. Only the game page now, but will add a start button instead of the game starting right away.
